[package]
name = "watchface-rs"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["watchface_rs_derive"]

[dependencies]
png = "0.17.13"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
winnow = "0.6.5"
watchface_rs_derive = { path = "watchface_rs_derive" }
